### ISSUE TITLE
Update logging of 'missing permissions' errors

### ISSUE THREAD

**Issue by benji7425** [benji7425/discord-activity-monitor#18]
Currently any and all errors associated with assigning roles get captured and sent to debug.log. Given just how often the error is that permissions are missing, this case should be handled differently.

- Prevent 'missing permissions' errors from being sent to debug.log
- Add explicit 'missing permissions' event log, rather than this information being lost in the generic 'ErrorMarkingActive' event

Example:
```
[20234] [Tue, 23 Jul 2019 19:56:27 GMT] [ERROR_DEBUG] Error marking user REDACTED active in guild REDACTED.
	Missing Permissions
	DiscordAPIError: Missing Permissions
    at item.request.gen.end (/home/benji/discord-activity-monitor/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:85:15)
    at then (/home/benji/discord-activity-monitor/node_modules/snekfetch/src/index.js:215:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by benji7425** [comment]
Fixed in bdedd0b46229e58cff8f397b61fe27e9ec6c8a44
Instead implemented by adding a 'code' field to the error logs, so later down the line we can filter out these errors. No longer logs to debug.log.
